services:
  server:
    build: ./server
    container_name: comichq_server
    restart: always
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M

  client:
    build: ./client
    container_name: comichq_client
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - server
    deploy:
      resources:
        limits:
          memory: 768M